mongo2:
  image: mongo:3.2.6
  hostname: mongo2
  restart: always
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest", "--httpinterface" ]
  ports:
    - "27217:27017"
    - "28217:28017"

mongo1:
  image: mongo:3.2.6
  hostname: mongo1
  restart: always
  entrypoint: [ "/usr/bin/mongod", "--replSet", "rs", "--journal", "--smallfiles", "--rest", "--httpinterface" ]
  ports:
    - "27117:27017"
    - "28117:28017"
  links:
    - mongo2:mongo2

es1:
  image: elasticsearch:2.3.3
  hostname: es1
  restart: always
  ulimits:
    memlock: -1
  environment:
    ES_HEAP_SIZE: 2g
    ES_JAVA_OPTS: >
      -Dbootstrap.mlockall=true·
      -Des.cluster.name=tractionBoard·
      -Des.transport.host=0.0.0.0
      -Des.network.host=0.0.0.0·
      -Des.node.name=es·
      -Des.node.master=true·
      -Des.node.data=true·
  ports:
    - "9201:9200"
    - "9301:9300"

es2:
  image: elasticsearch:2.3.3
  hostname: es2
  restart: always
  ulimits:
    memlock: -1
  environment:
    ES_HEAP_SIZE: 2g
    ES_JAVA_OPTS: >
      -Dbootstrap.mlockall=true·
      -Des.cluster.name=tractionBoard·
      -Des.transport.host=0.0.0.0
      -Des.network.host=0.0.0.0·
      -Des.node.name=es·
      -Des.node.master=true·
      -Des.node.data=true·
  ports:
    - "9202:9200"
    - "9302:9300"

# This configures the MongoDB 
setupmongodb:
  image: mongo:3.2.6
  links:
    - mongo1:mongo1
    - mongo2:mongo2
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup-mongodb.sh" ]

# This configures the ES
setupes:
  image: elasticsearch:2.3.3
  links:
    - es1:es1
    - es2:es2
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup-es.sh" ]

